Content.destroy_all
Content.create id: 'home-content-1', content: "Empower your agency with power of TripPro®"
Content.create id: 'home-content-2', content: "Discover revolutionary next generation search, book<br>and ticketing technology providing the best international fares."
Content.create id: 'home-content-3', content: "Advanced Booking Tools"
Content.create id: 'home-content-4', content: "Automated Ticketing"
Content.create id: 'home-content-5', content: "Profit Manager"
Content.create id: 'home-content-6', content: "Reporting & Analytics"
Content.create id: 'home-content-7', content: "More itineraries from multiple consolidators."
Content.create id: 'home-content-8', content: "Confirm and ticket instantly. It’s that simple."
Content.create id: 'home-content-9', content: "Exclusive content from Mondee consolidators all on one screen."
Content.create id: 'home-content-10', content: "Exclusive content from Mondee consolidators all on one screen."
Content.create id: 'home-content-11', content: "More savings for customers, more profit for you."
Content.create id: 'home-content-12', content: "TripPro gives you the best international fares, lets you save search time"
Content.create id: 'home-content-13', content: "and automate ticketing, which result in new sales, increased profits and happy customers."
Content.create id: 'home-content-14', content: "30% more"
Content.create id: 'home-content-15', content: "save 10h"
Content.create id: 'home-content-16', content: "10% increase"
Content.create id: 'home-content-17', content: "50% faster"
Content.create id: 'home-content-18', content: "unique itineraries"
Content.create id: 'home-content-19', content: "per agent on average"
Content.create id: 'home-content-20', content:  "in agency profits"
Content.create id: 'home-content-21', content: "ticket reservations"
Content.create id: 'home-content-22', content: "Benefits at your service"
Content.create id: 'home-content-23', content: "Maximize Profits"
Content.create id: 'home-content-24', content: "Easy to Use"
Content.create id: 'home-content-25', content: "Saves Time"
Content.create id: 'home-content-26', content: "Price Assurance"
Content.create id: 'home-content-27', content: "Experience and Trust"
Content.create id: 'home-content-28', content: "Complete control over commission and profit with one click access to unparalleled consolidator inventory."
Content.create id: 'home-content-29', content: "Fares displayed seamlessly via browser
												or with anypreferred GDS partner on
												the same screen, no training needed."
Content.create id: 'home-content-30', content: "One-click booking eliminates manual
												processing time and reduces new
												agent training time."
Content.create id: 'home-content-31', content: "Fares from the world’s leading
												consolidators, available instantly."
Content.create id: 'home-content-32', content: "Built for travel professionals by travel experts
												with over 120 years of experience
												helping agencies grow."
Content.create id: 'home-content-33', content: "Ready for a journey?"
Content.create id: 'home-content-34', content: "Benefits at your service"
Content.create id: 'home-content-35', content: "Benefits at your service"
Content.create id: 'home-content-36', content: "Benefits at your service"
Content.create id: 'home-content-37', content: "Benefits at your service"
Content.create id: 'home-content-38', content: "Benefits at your service"
Content.create id: 'home-content-39', content: "Benefits at your service"
Content.create id: 'home-content-40', content: "Benefits at your service"
Content.create id: 'home-content-41', content: "Benefits at your service"
Content.create id: 'home-content-42', content: "Benefits at your service"
Content.create id: 'home-content-43', content: "Benefits at your service"
Content.create id: 'home-content-44', content: "Benefits at your service"
Content.create id: 'home-content-45', content: "Benefits at your service"
Content.create id: 'home-content-46', content: "Benefits at your service"