Content.destroy_all
Content.create id: 'home-content-1', content: "Empower your agency with power of TripPro®"
Content.create id: 'home-content-2', content: "Discover revolutionary next generation search, book<br>and ticketing technology providing the best international fares."
Content.create id: 'home-content-3', content: "Advanced Booking Tools"
Content.create id: 'home-content-4', content: "Automated Ticketing"
Content.create id: 'home-content-5', content: "Profit Manager"
Content.create id: 'home-content-6', content: "Reporting & Analytics"
Content.create id: 'home-content-7', content: "More itineraries from multiple consolidators."
Content.create id: 'home-content-8', content: "Confirm and ticket instantly. It’s that simple."
Content.create id: 'home-content-9', content: "Exclusive content from Mondee consolidators all on one screen."
Content.create id: 'home-content-10', content: "Exclusive content from Mondee consolidators all on one screen."
Content.create id: 'home-content-11', content: "More savings for customers, more profit for you."
Content.create id: 'home-content-12', content: "TripPro gives you the best international fares, lets you save search time"
Content.create id: 'home-content-13', content: "and automate ticketing, which result in new sales, increased profits and happy customers."
Content.create id: 'home-content-14', content: "30% more"
Content.create id: 'home-content-15', content: "save 10h"
Content.create id: 'home-content-16', content: "10% increase"
Content.create id: 'home-content-17', content: "50% faster"
Content.create id: 'home-content-18', content: "unique itineraries"
Content.create id: 'home-content-19', content: "per agent on average"
Content.create id: 'home-content-20', content:  "in agency profits"
Content.create id: 'home-content-21', content: "ticket reservations"
